// Generated by scripts/voice-clips.mjs. Do not edit.
window.ALGO_VOICE_CLIPS = {
  "complete": "voice/clips/complete.m4a",
  "greeting": "voice/clips/greeting.m4a",
  "joke-answer-fr": "voice/clips/joke-answer-fr.m4a",
  "joke-question": "voice/clips/joke-question.m4a",
  "new-ideas": "voice/clips/new-ideas.m4a",
  "world-welcome": "voice/clips/world-welcome.m4a"
};
