#!/usr/bin/env node
// Turns voice/lines.json + voice/clips/*.{webm,m4a,mp3,wav} into everything the apps need:
//   mobile/src/voice/lines.ts             the lines with ids (TTS text and recording script)
//   mobile/src/voice/clips.generated.ts   require() map of the recorded clips (copied to mobile/assets/voice)
//   voice/clips.js                        window.ALGO_VOICE_CLIPS for the web prototype and Algo World
// Lines without a clip fall back to text-to-speech at run time. Run: npm run voice
import { readFileSync, writeFileSync, readdirSync, mkdirSync, copyFileSync, existsSync, rmSync } from 'node:fs';
import { join, extname, basename } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const { lines } = JSON.parse(readFileSync(join(root, 'voice', 'lines.json'), 'utf8'));
const clipDir = join(root, 'voice', 'clips');
const assetDir = join(root, 'mobile', 'assets', 'voice');
const extensions = ['.m4a', '.mp3', '.wav', '.webm', '.ogg'];
const ids = new Set(lines.map(l => l.id));

// One clip per id; prefer m4a (plays on iPhone too) over webm.
const clips = new Map();
if (existsSync(clipDir)) {
  for (const file of readdirSync(clipDir).sort()) {
    const ext = extname(file).toLowerCase();
    const id = basename(file, ext);
    if (!extensions.includes(ext)) continue;
    if (!ids.has(id)) { console.warn(`voice/clips/${file}: no line with id "${id}" in voice/lines.json (ignored)`); continue; }
    const current = clips.get(id);
    if (!current || extensions.indexOf(ext) < extensions.indexOf(extname(current).toLowerCase())) clips.set(id, file);
  }
}

// lines.ts
const linesTs = `// Generated by scripts/voice-clips.mjs from voice/lines.json. Do not edit; edit the JSON.
// Each id is what a recorded clip is filed under (voice/clips/<id>.m4a). Build steps and
// hints are spoken from App.tsx's builds with ids \`\${buildId}-step-\${n}\` and \`\${buildId}-hint-\${n}\`.
export const LINES = {
${lines.map(l => `  ${/^[a-z]+$/.test(l.id) ? l.id : `'${l.id}'`}: ${JSON.stringify(l.text)},`).join('\n')}
} as const;

export const LINE_LANGUAGE: Partial<Record<LineId, 'en-US' | 'fr-FR'>> = {
${lines.filter(l => l.language).map(l => `  '${l.id}': '${l.language}',`).join('\n')}
};

export type LineId = keyof typeof LINES;
`;
writeFileSync(join(root, 'mobile', 'src', 'voice', 'lines.ts'), linesTs);

// mobile assets + require map
rmSync(assetDir, { recursive: true, force: true });
mkdirSync(assetDir, { recursive: true });
for (const [, file] of clips) copyFileSync(join(clipDir, file), join(assetDir, file));
const clipsTs = `// Generated by scripts/voice-clips.mjs. Do not edit: drop recordings in voice/clips and run npm run voice.
// eslint-disable
export const CLIPS: Record<string, number> = {
${[...clips].map(([id, file]) => `  '${id}': require('../../assets/voice/${file}'),`).join('\n')}
};
`;
writeFileSync(join(root, 'mobile', 'src', 'voice', 'clips.generated.ts'), clipsTs);

// web map (paths relative to the site root; index.html and world/ both resolve them)
const clipsJs = `// Generated by scripts/voice-clips.mjs. Do not edit.
window.ALGO_VOICE_CLIPS = ${JSON.stringify(Object.fromEntries([...clips].map(([id, file]) => [id, `voice/clips/${file}`])), null, 2)};
`;
writeFileSync(join(root, 'voice', 'clips.js'), clipsJs);

console.log(`${lines.length} lines, ${clips.size} recorded: ${[...clips.keys()].join(', ') || '(none yet, TTS everywhere)'}`);
const missing = lines.filter(l => !clips.has(l.id)).map(l => l.id);
if (missing.length) console.log(`still to record: ${missing.join(', ')}`);
