// Generated by scripts/voice-clips.mjs. Do not edit: drop recordings in voice/clips and run npm run voice.
// eslint-disable
export const CLIPS: Record<string, number> = {
  'complete': require('../../assets/voice/complete.m4a'),
  'greeting': require('../../assets/voice/greeting.m4a'),
  'joke-answer-fr': require('../../assets/voice/joke-answer-fr.m4a'),
  'joke-question': require('../../assets/voice/joke-question.m4a'),
  'new-ideas': require('../../assets/voice/new-ideas.m4a'),
  'world-welcome': require('../../assets/voice/world-welcome.m4a'),
};
