// Generated by scripts/voice-clips.mjs from voice/lines.json. Do not edit; edit the JSON.
// Each id is what a recorded clip is filed under (voice/clips/<id>.m4a). Build steps and
// hints are spoken from App.tsx's builds with ids `${buildId}-step-${n}` and `${buildId}-hint-${n}`.
export const LINES = {
  greeting: "Hi! I’m Algo. Let’s build something amazing!",
  'world-welcome': "Welcome to Algo World! Let’s explore!",
  'joke-question': "Pourquoi les briques sont-elles heureuses?",
  'joke-answer-fr': "Parce qu’elles s’emboîtent bien!",
  'joke-answer-en': "That means: because they fit together well!",
  'ideas-demo': "Here are three things we can build!",
  'new-ideas': "Voilà! Three new ideas!",
  'scan-looking': "Let me look at your pieces.",
  complete: "Bravo! Magnifique! You built it!",
  'invention-complete': "Bravo! Your invention is one of a kind!",
  'book-ready': "Your real instruction book is ready. Let’s turn the pages!",
  'creator-welcome': "I can’t wait to see what you invent!",
  'world-gameover': "Oh no! Let’s try again!",
  'world-apple': "Yum, an apple!",
} as const;

export const LINE_LANGUAGE: Partial<Record<LineId, 'en-US' | 'fr-FR'>> = {
  'joke-question': 'fr-FR',
  'joke-answer-fr': 'fr-FR',
};

export type LineId = keyof typeof LINES;
